Maps
antoinech2/Le-jeu-de-la-MP pull request #20
Opened 2021-12-01 21:32 UTC by Djessbourg

2021-12-01 22:24 UTC, antoinech2 approved these changes

2021-12-01 22:27 UTC, fmkr-project approved these changes

2021-12-02 07:33 UTC, Ordralfabetix approved these changes

2021-12-02 07:40 UTC, Ordralfabetix requested changes
Erreur lors de l'appui sur la barre espace, le jeu quitte subitement:
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/mateo/Documents/PROGRAMMATION/prepa-simulator/src/main.py", line 15, in <module>
    game.run()
  File "/home/mateo/Documents/PROGRAMMATION/prepa-simulator/src/game.py", line 69, in run
    inputs.handle_key_down_event(self, event)
  File "/home/mateo/Documents/PROGRAMMATION/prepa-simulator/src/inputs.py", line 12, in handle_key_down_event
    game.player.space_pressed()
  File "/home/mateo/Documents/PROGRAMMATION/prepa-simulator/src/player.py", line 83, in space_pressed
    self.dialogue.input_from_player()
  File "/home/mateo/Documents/PROGRAMMATION/prepa-simulator/src/dialogue.py", line 50, in input_from_player
    self.game.player.can_talk()
  File "/home/mateo/Documents/PROGRAMMATION/prepa-simulator/src/player.py", line 87, in can_talk
    if pg.sprite.spritecollide(self, self.game.map.group_npc, False):
AttributeError: 'Game' object has no attribute 'map'
```

2021-12-04 14:36 UTC, Ordralfabetix requested changes
Impossible de lancer le jeu :
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/mateo/prepa-simulator/src/main.py", line 14, in <module>
    game = game.Game()
  File "/home/mateo/prepa-simulator/src/game.py", line 27, in __init__
    self.map_manager = maps.MapManager(self.screen, self.player)
  File "/home/mateo/prepa-simulator/src/maps.py", line 56, in __init__
    self.register_map( "l101", "la_kro",
  File "/home/mateo/prepa-simulator/src/maps.py", line 94, in register_map
    tmx_data = pytmx.util_pygame.load_pygame(f"res/maps/{name_map}.tmx")    # name_map doit bien entendu correspondre au nom du fichier tmx (resp pour name_music en mp3)
  File "/home/mateo/.local/lib/python3.9/site-packages/pytmx/util_pygame.py", line 183, in load_pygame
    return pytmx.TiledMap(filename, *args, **kwargs)
  File "/home/mateo/.local/lib/python3.9/site-packages/pytmx/pytmx.py", line 492, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "/home/mateo/.local/lib/python3.9/site-packages/pytmx/pytmx.py", line 541, in parse_xml
    self.add_tileset(TiledTileset(self, subnode))
  File "/home/mateo/.local/lib/python3.9/site-packages/pytmx/pytmx.py", line 1092, in __init__
    self.parse_xml(node)
  File "/home/mateo/.local/lib/python3.9/site-packages/pytmx/pytmx.py", line 1118, in parse_xml
    raise Exception(
Exception: Cannot find tileset file ../../../../Documents/prepa-simulator/res/textures/tiles.tsx from res/maps/l101.tmx, should be at /home/Documents/prepa-simulator/res/textures/tiles.tsx
```

2021-12-04 14:43 UTC, Ordralfabetix approved these changes

2021-12-11 18:49 UTC, merged